name: heroics
description: Heroics is the ultimate character creation and management tool for tabletop role-playing games

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_native_splash: ^2.2.17

  # Firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_analytics: ^10.1.0
  firebase_crashlytics: ^3.0.11
  firebase_remote_config: ^3.0.9
  firebase_dynamic_links: ^5.0.11
  firebase_performance: ^0.9.0+10

  logger: ^1.1.0
  flutter_bloc: ^8.1.1
  rxdart: ^0.27.7
  provider: ^6.0.5
  freezed_annotation: ^2.2.0
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  #  bloc_test: ^9.1.0
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700