// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0bKkrJAMsLtCtnhwHfrntXKMPMDcNaKM',
    appId: '1:702781374001:web:02b0960a23b6f0d03d5f10',
    messagingSenderId: '702781374001',
    projectId: 'dnd5-charactersheet',
    authDomain: 'dnd5-charactersheet.firebaseapp.com',
    databaseURL: 'https://dnd5-charactersheet-default-rtdb.firebaseio.com',
    storageBucket: 'dnd5-charactersheet.appspot.com',
    measurementId: 'G-32F0FGZD2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJjvwFjSCfeI-7RgmJ2gqdKQ-Ul-pqee8',
    appId: '1:702781374001:android:712cc505112d2af83d5f10',
    messagingSenderId: '702781374001',
    projectId: 'dnd5-charactersheet',
    databaseURL: 'https://dnd5-charactersheet-default-rtdb.firebaseio.com',
    storageBucket: 'dnd5-charactersheet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOTl0oM1agWQQTRLYiH5YpVUNs9wrZ7vc',
    appId: '1:702781374001:ios:04f2f0f7d67adf2e3d5f10',
    messagingSenderId: '702781374001',
    projectId: 'dnd5-charactersheet',
    databaseURL: 'https://dnd5-charactersheet-default-rtdb.firebaseio.com',
    storageBucket: 'dnd5-charactersheet.appspot.com',
    iosClientId: '702781374001-vcv85g5edalqnr2ic3rk1sdhpdm3r5h4.apps.googleusercontent.com',
    iosBundleId: 'cacao.dao.heroics',
  );
}
